#!/usr/bin/env bash
# Build a gh config directory holding exactly ONE GitHub account, and print the
# GH_CONFIG_DIR line to put in .claude/settings.local.json.
#
# ── Why ────────────────────────────────────────────────────────────────────
#
# `gh auth switch` changes the active account in a SHARED config file. There is
# no per-session scope: every process on the machine, including sessions a
# human is watching and agent sessions nobody is, starts speaking as the new
# account from that moment. A second account signed in for unrelated work is
# therefore not passive -- it is one command away from authoring things.
#
# Measured on this repo, 2026-09-05: a corp account had authored one issue and
# three comments on the PUBLIC repo, across three days spanning eleven. Nothing
# failed. `gh issue comment` prints a URL, not an identity, so the mistake was
# invisible from inside the session that made it.
#
# `.claude/hooks/gh-account-guard.sh` catches that at the tool boundary. This
# script removes the possibility instead: a config directory that does not
# CONTAIN the other account cannot be switched to it --
#
#     $ GH_CONFIG_DIR=<scoped> gh auth switch --user <other>
#     no accounts matched that criteria
#
# which is the difference between a rule that is checked and one that cannot be
# broken. Both layers are kept: this one is per-machine and can be forgotten in
# a fresh clone, the hook travels with the repo.
#
# ⚠️ No secret is copied or created. gh keeps tokens in the OS keyring and
# hosts.yml holds only the account NAME, so the directory this writes is safe
# to inspect and worthless to steal.
set -eu

OWNER_DEFAULT="gjovanov"
OWNER="${1-$OWNER_DEFAULT}"
DEST="${2-$HOME/.config/gh-roomler}"

command -v gh >/dev/null 2>&1 || { echo "gh is not on PATH" >&2; exit 1; }

# Locate the CURRENT config so config.yml (aliases, editor, prompt settings)
# carries over. Only hosts.yml is rewritten.
SRC=""
for cand in "${GH_CONFIG_DIR:-}" "${XDG_CONFIG_HOME:-}/gh" "${APPDATA:-}/GitHub CLI" "$HOME/.config/gh"; do
  case "$cand" in (''|/gh|"/GitHub CLI") continue ;; esac
  [ -f "$cand/hosts.yml" ] && { SRC="$cand"; break; }
done
[ -n "$SRC" ] || { echo "could not find an existing gh config (no hosts.yml)" >&2; exit 1; }

mkdir -p "$DEST"

# ⚠️ SRC and DEST can be the SAME directory, and that is the normal case on the
# second run: once GH_CONFIG_DIR points at the scoped config, the search above
# finds it first. Copying a file onto itself is an error under `set -e`, so a
# script that did not check this worked exactly once and then failed forever --
# which for a setup script means it is never re-run, and its checks below never
# run again either.
same_dir() {
  [ "$(cd "$1" 2>/dev/null && pwd -P)" = "$(cd "$2" 2>/dev/null && pwd -P)" ]
}
if [ -f "$SRC/config.yml" ] && ! same_dir "$SRC" "$DEST"; then
  cp "$SRC/config.yml" "$DEST/config.yml"
fi

cat > "$DEST/hosts.yml" <<EOF
# Scoped gh config -- generated by scripts/gh-scoped-config.sh.
#
# Deliberately lists ONE account. A second account here re-creates the whole
# failure this directory exists to prevent: \`gh auth switch\` mutates the
# active account GLOBALLY, so any concurrent session can be re-identified
# underneath it and post as the wrong person.
#
# Tokens live in the OS keyring, not in this file.
github.com:
    git_protocol: https
    users:
        $OWNER:
    user: $OWNER
EOF

# ⚠️ Verify by USE, not by inspection. The keyring entry is looked up by host
# and account, so a hand-written hosts.yml that names an account whose token
# was never stored produces a directory that looks perfectly correct and
# authenticates as nobody. Ask the API who it is.
got="$(GH_CONFIG_DIR="$DEST" gh api user --jq .login 2>/dev/null || true)"
if [ "$got" != "$OWNER" ]; then
  echo "FAILED: the scoped config authenticates as '${got:-nobody}', not '$OWNER'." >&2
  echo "        Run: GH_CONFIG_DIR=$DEST gh auth login   (then re-run this script)" >&2
  exit 1
fi

# And verify the property that is the whole point, rather than assuming it.
if GH_CONFIG_DIR="$DEST" gh auth switch --user "$OWNER_DEFAULT-other" >/dev/null 2>&1; then
  echo "FAILED: the scoped config could be switched to another account." >&2
  exit 1
fi

cat <<EOF
Scoped gh config ready: $DEST
  authenticates as : $got
  switchable to    : nothing else

Add this to .claude/settings.local.json (which is gitignored, because the path
is machine-specific):

  {
    "env": {
      "GH_CONFIG_DIR": "$DEST"
    }
  }

Then in a NEW session, confirm both halves:

  gh api user --jq .login          # -> $OWNER
  gh auth switch --user <other>    # -> no accounts matched that criteria
EOF

# ── the rest of the LOCAL half, reported rather than assumed ───────────────
#
# Two of the four identity layers are per-clone configuration, not code, so
# they do not arrive with a `git clone` and nothing fails when they are absent.
# That is the failure mode this repo has already paid for twice: `core.hooksPath`
# left unset made the machine-name hook inert in ~53 worktrees while working
# perfectly in the main clone, and a `.claude/` ignore rule silently swallowed
# the whole sanitisation skill for a session.
#
# So the status is PRINTED. An unwired clone is then loud rather than merely
# unprotected -- the CI job still refuses the merge either way, but nobody
# learns that from a hook that never ran.
REPO="$(git rev-parse --show-toplevel 2>/dev/null || echo .)"
echo
echo "Local guard wiring in $REPO:"

hp="$(git -C "$REPO" config --get core.hooksPath 2>/dev/null || true)"
if [ "$hp" = ".githooks" ]; then
  echo "  [ok]      core.hooksPath = .githooks   (pre-commit + pre-push active)"
else
  echo "  [MISSING] core.hooksPath is '${hp:-unset}' -- the commit-identity and"
  echo "            machine-name hooks DO NOT RUN in this clone. Fix:"
  echo "                git -C '$REPO' config core.hooksPath .githooks"
fi

# The PreToolUse hook is wired in .claude/settings.json, which is deliberately
# untracked (everything under .claude/ is local except the tooling itself), so
# a fresh clone has the hook SCRIPT but no wiring to invoke it.
if grep -q 'gh-account-guard.sh' "$REPO/.claude/settings.json" 2>/dev/null; then
  echo "  [ok]      PreToolUse hook wired in .claude/settings.json"
else
  echo "  [MISSING] the GitHub-write guard is not wired. .claude/settings.json is"
  echo "            untracked by design, so this does not arrive with a clone. Add:"
  cat <<'WIRING'
                "hooks": {
                  "PreToolUse": [
                    { "matcher": "Bash",
                      "hooks": [ { "type": "command",
                        "command": "bash \"$CLAUDE_PROJECT_DIR/.claude/hooks/gh-account-guard.sh\"" } ] }
                  ]
                }
WIRING
fi
