// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (C) 2026 G ROX EOOD
/**
 * FR-87 (#1776) — content-hashed asset names.
 *
 * The pod serves every `.js`/`.css`/`.svg`/`.png`… with
 * `Cache-Control: public, immutable` and a one-year expiry
 * (`files/nginx-pod.conf`, the `\.(?:js|css|…)$` location). That promise only
 * holds for a name that changes when its bytes do. FR-60 published `docs.css`,
 * `search.js` and every hero under FIXED names, so a returning reader kept the
 * stylesheet they first downloaded, against whatever HTML came after it.
 *
 * Every asset the generator publishes is now `name.<sha256:10>.ext`, and the
 * HTML (revalidated on every load since P1) is what moves readers to new bytes.
 *
 * Planned first, written last: pages are loaded — and their images resolved —
 * BEFORE build.ts empties `dist/docs`, so `publish*` only records, and
 * `flush()` writes once the output directory is fresh.
 */
import { createHash } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { basename, extname, join } from 'node:path'

export const HASH_LEN = 10

export function contentHash(bytes: Uint8Array | string): string {
  return createHash('sha256').update(bytes).digest('hex').slice(0, HASH_LEN)
}

/** `docs.css` + bytes -> `docs.<hash>.css`. */
export function hashedName(name: string, bytes: Uint8Array | string): string {
  const ext = extname(name)
  return `${name.slice(0, name.length - ext.length)}.${contentHash(bytes)}${ext}`
}

interface Planned {
  name: string
  bytes: Uint8Array | string
  /** Also publish under the plain name (see `legacy` below). */
  legacyName?: string
}

export class AssetEmitter {
  private readonly planned = new Map<string, Planned>()
  private readonly bySource = new Map<string, string>()

  /**
   * @param urlBase site-absolute URL of `outDir`, e.g. `/docs/assets`
   * @param legacy also publish each file under its OLD, unhashed name. HTML a
   *   browser cached before FR-87 P1 made pages revalidate still names those
   *   files; this keeps them loading for the one release it takes that HTML
   *   to age out. Turned off by `LEGACY_UNHASHED_ASSETS` in site.ts.
   */
  constructor(
    private readonly outDir: string,
    private readonly urlBase: string,
    private readonly legacy: boolean,
  ) {}

  /** Plans a file from disk under its hashed name and returns its URL.
   *  The same source always maps to the same URL. */
  publishFile(src: string): string {
    const known = this.bySource.get(src)
    if (known) return known
    const bytes = readFileSync(src)
    const url = this.plan(basename(src), bytes)
    this.bySource.set(src, url)
    return url
  }

  /** Plans generated bytes (the search index) under a hashed `name`. */
  publishBytes(name: string, bytes: Uint8Array | string): string {
    return this.plan(name, bytes)
  }

  private plan(name: string, bytes: Uint8Array | string): string {
    const hashed = hashedName(name, bytes)
    const legacyName = this.legacy ? name : undefined
    // Two different files that share a basename would fight over the legacy
    // name. Their hashed names differ, so only the legacy copy is ambiguous —
    // and silently shipping the wrong one is exactly what hashing is for
    // avoiding. Refuse instead.
    if (legacyName) {
      for (const p of this.planned.values()) {
        if (p.legacyName === legacyName && p.name !== hashed) {
          throw new Error(
            `two different assets are both named "${name}" — rename one ` +
              `(the unhashed legacy copy can only be one of them)`,
          )
        }
      }
    }
    this.planned.set(hashed, { name: hashed, bytes, legacyName })
    return `${this.urlBase}/${hashed}`
  }

  /** Published file names (hashed, then legacy), sorted — for tests and the log. */
  names(): string[] {
    const out: string[] = []
    for (const p of this.planned.values()) {
      out.push(p.name)
      if (p.legacyName) out.push(p.legacyName)
    }
    return out.sort()
  }

  flush(): void {
    mkdirSync(this.outDir, { recursive: true })
    for (const p of this.planned.values()) {
      writeFileSync(join(this.outDir, p.name), p.bytes)
      if (p.legacyName) writeFileSync(join(this.outDir, p.legacyName), p.bytes)
    }
  }
}
